package io.github.hassandomedenea.aliassourcenavigator;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

final class GeneratedAliasParserTest {
    @Test
    void parsesAutoImportedComposable() {
        GeneratedAliasParser.AliasTarget target = GeneratedAliasParser.find(
            "const useAuth: typeof import('../modules/auth/authStore').useAuth",
            "useAuth"
        );

        assertEquals("../modules/auth/authStore", target.modulePath());
        assertEquals("useAuth", target.exportName());
    }

    @Test
    void parsesAutoImportedComponent() {
        GeneratedAliasParser.AliasTarget target = GeneratedAliasParser.find(
            "LoginForm: typeof import('./../modules/auth/LoginForm.vue')['default']",
            "LoginForm"
        );

        assertEquals("./../modules/auth/LoginForm.vue", target.modulePath());
        assertEquals("default", target.exportName());
    }

    @Test
    void ignoresDifferentSymbols() {
        GeneratedAliasParser.AliasTarget target = GeneratedAliasParser.find(
            "const useAuth: typeof import('../modules/auth/authStore').useAuth",
            "useTestStore"
        );

        assertNull(target);
    }

    @Test
    void findsAliasesByTheirSourceExportName() {
        String declarations = """
            const useNavigationTools: typeof import('../modules/shared/navigation/navigationTools').useNavigationTools
            const useAuthStore: typeof import('../modules/auth/authStore').useAuthStore
            const auth: typeof import('../modules/auth/authStore')['useAuthStore']
            """;

        List<GeneratedAliasParser.AliasTarget> targets = GeneratedAliasParser.findByExportName(
            declarations,
            "useAuthStore"
        );

        assertEquals(2, targets.size());
        assertEquals("useAuthStore", targets.getFirst().symbolName());
        assertEquals("../modules/auth/authStore", targets.getFirst().modulePath());
        assertEquals("useAuthStore", targets.getFirst().exportName());
        assertEquals(declarations.indexOf("useAuthStore:"), targets.getFirst().symbolOffset());
    }

    @Test
    void findsRealMultilineAutoImportDeclaration() {
        String declarations = """
            /* generated by unplugin-auto-import */
            declare global {
              const useNavigationTools: typeof import(
                '../modules/shared/navigation/navigationTools'
              ).useNavigationTools
            }
            """;

        GeneratedAliasParser.AliasTarget target = GeneratedAliasParser.find(
            declarations,
            "useNavigationTools"
        );

        assertEquals("../modules/shared/navigation/navigationTools", target.modulePath());
        assertEquals("useNavigationTools", target.exportName());
    }
}
