package io.github.hassandomedenea.aliassourcenavigator;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class WayfinderTsExportResolverTest {
    private static final String CONTROLLER_TS = """
        // This file is auto-generated by Laravel Wayfinder.

        /**
         * @see \\App\\Modules\\Patients\\PatientController::autocomplete
         * @see \\E:\\Herd\\hddclinic4\\app\\Modules\\Patients\\PatientController.php:52
         * @route "/api/patients/autocomplete"
         */
        export const autocomplete = (options) => ({
            url: autocomplete.url(options),
            method: "get",
        })

        /**
         * @see \\App\\Modules\\Patients\\PatientController::query
         * @see \\E:\\Herd\\hddclinic4\\app\\Modules\\Patients\\PatientController.php:19
         * @route "/api/patients/query"
         */
        export const query = (options) => ({
            url: query.url(options),
            method: "post",
        })

        const PatientController = {
            autocomplete,
            query,
        }

        export default PatientController
        """;

    @Test
    void findsNamedExportOffsetNotDefaultObject() {
        Integer offset = WayfinderTsExportResolver.namedExportOffset(CONTROLLER_TS, "autocomplete");

        assertNotNull(offset);
        assertEquals(CONTROLLER_TS.indexOf("export const autocomplete") + "export const ".length(), offset);

        int objectOffset = CONTROLLER_TS.lastIndexOf("autocomplete");
        assertTrue(offset < objectOffset);
    }

    @Test
    void returnsNullForControllerObjectName() {
        assertNull(WayfinderTsExportResolver.namedExportOffset(CONTROLLER_TS, "PatientController"));
    }

    @Test
    void findsQueryExport() {
        Integer offset = WayfinderTsExportResolver.namedExportOffset(CONTROLLER_TS, "query");
        assertNotNull(offset);
        assertEquals(CONTROLLER_TS.indexOf("export const query") + "export const ".length(), offset);
    }
}
