package io.github.hassandomedenea.aliassourcenavigator;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class WayfinderGeneratedDetectorTest {
    @Test
    void detectsPathMarker() {
        assertTrue(containsPathMarker("E:/Herd/hddclinic4/resources/js/generated/wayfinder/App/Modules/Patients/PatientController.ts"));
        assertTrue(containsPathMarker("E:\\Herd\\hddclinic4\\resources\\js\\generated\\wayfinder\\App\\Modules\\Patients\\PatientController.ts"));
        assertFalse(containsPathMarker("E:/Herd/hddclinic4/resources/js/pages/login.vue"));
    }

    @Test
    void detectsHeaderMarker() {
        String header = """
            // This file is auto-generated by Laravel Wayfinder.
            // Do not edit this file directly, any changes will be overwritten.
            """;
        assertTrue(header.contains("auto-generated by Laravel Wayfinder"));
        assertFalse("// regular file".contains("auto-generated by Laravel Wayfinder"));
    }

    private static boolean containsPathMarker(String path) {
        return path.replace('\\', '/').toLowerCase().contains("generated/wayfinder");
    }
}
