package io.github.hassandomedenea.aliassourcenavigator;

import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.PsiFile;
import org.jetbrains.annotations.Nullable;

final class WayfinderGeneratedDetector {
    private static final String PATH_MARKER = "generated/wayfinder";
    private static final String HEADER_MARKER = "auto-generated by Laravel Wayfinder";

    private WayfinderGeneratedDetector() {
    }

    static boolean isWayfinderFile(@Nullable PsiFile file) {
        if (file == null) {
            return false;
        }

        VirtualFile virtualFile = file.getVirtualFile();
        if (virtualFile != null) {
            String path = virtualFile.getPath().replace('\\', '/').toLowerCase();
            if (path.contains(PATH_MARKER)) {
                return true;
            }
        }

        String text = file.getText();
        if (text == null || text.isEmpty()) {
            return false;
        }

        int probeLength = Math.min(text.length(), 512);
        return text.substring(0, probeLength).contains(HEADER_MARKER);
    }
}
